# Generated by Django 5.2.15 on 2026-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_recyclingcenterprofile_staffprofile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=100, unique=True)),
                ('location', models.TextField()),
                ('waste_type', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('current_level', models.FloatField(default=0)),
                ('status', models.CharField(default='empty', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
