# Generated by Django 5.2.15 on 2026-06-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pickuprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wastebin')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('collection_status', models.CharField(default='assigned', max_length=50)),
                ('collected_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pickuprequest')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WasteCollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('total_quantity', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recycling_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.recyclingcenterprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collectiontask')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.recyclingcenterprofile')),
                ('waste_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wastecollectionrecord')),
            ],
        ),
    ]
